
<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Arsip extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Arsip_model');    
        if (!$this->ion_auth->logged_in()) {
            redirect('auth','refresh');
        }    
        
    }

    function index($idcmbdosen=NULL)
    {
        if($this->ion_auth->is_admin()){
            $datadosen = $this->db->query("SELECT * FROM dosen")->result_array();
            if(isset($_POST['btnCari']) || $this->uri->segment('3')<>'') {
                
                if($this->uri->segment('3')<>''){
                    $idDosen = $this->uri->segment('3');
                    $data['urisegment'] = $this->uri->segment('3');
                } else {
                    $idDosen = $_POST['cmbDosen'];
                }
                $q_arsip = $this->db->query("SELECT a.*,
                (SELECT ad.terakhir_diubah FROM arsip_dosen ad WHERE ad.id_arsip=a.id AND ad.id_dosen='$idDosen') AS terakhir_diubah,
                (SELECT ad.url FROM arsip_dosen ad WHERE ad.id_arsip=a.id AND ad.id_dosen='$idDosen') AS url,
                (SELECT ad.id FROM arsip_dosen ad WHERE ad.id_arsip=a.id AND ad.id_dosen='$idDosen') AS idarsipdosen
                FROM arsip a")->result_array();
                $q_foto = $this->db->query("SELECT a.*,
                (SELECT ad.url FROM arsip_dosen ad JOIN dosen d ON d.id=ad.id_dosen WHERE ad.id_arsip=a.id AND d.id='$idDosen') AS url
                FROM arsip a WHERE a.nama_dokumen='FOTO'")->row()->url;
                $q_info = $this->db->query("SELECT * FROM dosen WHERE id='$idDosen'");
                if($q_info->num_rows()>0){
                    $nama = $q_info->row()->nama;
                    $nip = $q_info->row()->nip;
                } else {
                    $nama = "NIP Yang Anda Masukkan Tidak Ditemukan";
                    $nip = "Silahkan Periksa Kembali";
                    $q_arsip = "";
                }
            } else {
                $q_arsip = "";
                $nama = "";
                $nip = "";
                $iddospeg = "";
            }
                
        } else {
            $datadosen = "";
            $userid = $this->ion_auth->user()->row()->id;
            $q_arsip = $this->db->query("SELECT a.*,
            (SELECT ad.terakhir_diubah FROM arsip_dosen ad JOIN dosen d ON d.id=ad.id_dosen WHERE ad.id_arsip=a.id AND d.userid='$userid') AS terakhir_diubah,
            (SELECT ad.url FROM arsip_dosen ad JOIN dosen d ON d.id=ad.id_dosen WHERE ad.id_arsip=a.id AND d.userid='$userid') AS url
            FROM arsip a")->result_array();
            $q_foto = $this->db->query("SELECT a.*,
            (SELECT ad.terakhir_diubah FROM arsip_dosen ad JOIN dosen d ON d.id=ad.id_dosen WHERE ad.id_arsip=a.id AND d.userid='$userid') AS terakhir_diubah,
            (SELECT ad.url FROM arsip_dosen ad JOIN dosen d ON d.id=ad.id_dosen WHERE ad.id_arsip=a.id AND d.userid='$userid') AS url
            FROM arsip a WHERE a.nama_dokumen='FOTO'")->row()->url;
            $q_info = $this->db->query("SELECT * FROM dosen WHERE userid='$userid'");
            $nama = $q_info->row()->nama;
            $nip = $q_info->row()->nip;
        } 
        $data['datadosen'] = $datadosen;
        $data['nama'] = $nama;
        $data['nip'] = $nip;
        $data['foto'] = $q_foto;
        $data['arsip'] = $q_arsip;
        $data['_view'] = 'arsip';
        $this->load->view('layouts/main',$data);
    }

    function upload()
    {
        $config['upload_path']   = FCPATH.'/uploads/';
        $config['allowed_types'] = 'gif|jpg|png|pdf|doc|jpeg|docx';
        $this->load->library('upload',$config);

        if($this->upload->do_upload('userfile')){
            $iddosen=$this->input->post('iddosen');
            $idarsip=$this->input->post('idarsip');
            $nama=$this->upload->data('file_name');
            $datetimenow = date('Y-m-d H:i:s');
            $url = 'uploads/'.$nama;
            $q_arsip = $this->db->query("SELECT a.id AS ArsipID, a.nama_dokumen, a.jenis_file, a.max_size, 
                (SELECT ad.terakhir_diubah FROM arsip_dosen ad JOIN dosen d ON d.id=ad.id_dosen WHERE id_arsip=a.id AND d.id='$iddosen') AS terakhir_diubah,
                (SELECT ad.url FROM arsip_dosen ad JOIN dosen d ON d.id=ad.id_dosen WHERE id_arsip=a.id AND d.id='$iddosen') AS url,
                (SELECT d.id FROM arsip_dosen ad JOIN dosen d ON d.id=ad.id_dosen WHERE id_arsip=a.id AND d.id='$iddosen') AS iddosen
                FROM arsip a");
            $query = $this->db->query("SELECT id FROM arsip_dosen WHERE id_arsip=$idarsip AND id_dosen=$iddosen");
            if($query->num_rows()==0){
                $this->db->insert('arsip_dosen',array('id_arsip'=>$idarsip, 'id_dosen'=>$iddosen,'terakhir_diubah'=>$datetimenow,'url'=>$url));
            } else {
                $id = $query->row()->id;
                $dataupdate = array('terakhir_diubah'=>$datetimenow, 'url'=>$url);
                $this->db->where('id',$id);
                $this->db->update('arsip_dosen',$dataupdate);
            }
        }   
    }

    function remove($idarsipdosen,$iddosen)
    {
        $this->db->delete('arsip_dosen',array('id'=>$idarsipdosen));
        redirect('arsip/index/'.$iddosen);
    }
}
