<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Beranda extends CI_Controller{
    function __construct()
    {
        parent::__construct();
    }

    function index()
    {
        $dospeg = $this->db->query("SELECT DISTINCT d.golongan,(SELECT count(golongan) FROM dosen WHERE golongan=d.golongan) as jumlah FROM dosen d")->result_array();
        $data['dospeg'] = $dospeg;
        $data['_view'] = 'beranda';
        $this->load->view('layouts/main',$data);
    }
}
