<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Informasi extends CI_Controller{
    function __construct()
    {
        parent::__construct();
    }

    function index()
    {
        $gol_dosen = $this->db->query("SELECT DISTINCT golongan FROM dospeg WHERE jenis_pd='dosen'")->result_array();
        $gol_pegawai = $this->db->query("SELECT DISTINCT golongan FROM dospeg WHERE jenis_pd='pegawai' ORDER BY golongan DESC")->result_array();
        $peraturan = $this->db->query("SELECT * FROM pengumuman WHERE kategori='peraturan' ORDER BY datetime DESC")->result_array();
        $data['peraturan'] = $peraturan;
        $data['gol_dosen'] = $gol_dosen;
        $data['gol_pegawai'] = $gol_pegawai;
        $data['_view'] = 'informasi';
        $this->load->view('layouts/main',$data);
    }
}
