<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Master_model extends CI_Model
{

    public $table = 'dospeg';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,nama,tempat_lahir,tgl_lahir,nip,nidn,jk,golongan,gol_tmt,jabatan,jabatan_tmt,masa_kerja_tahun,masa_kerja_bulan,pendidikan,tahun_lulus,tingkat_ijazah,usia,catatan_mutasi,jenis_pd,userid');
        $this->datatables->from('dospeg');
        //add this line for join
        //$this->datatables->join('table2', 'dospeg.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('master/read/$1'),'Read')." | ".anchor(site_url('master/update/$1'),'Update')." | ".anchor(site_url('master/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('tempat_lahir', $q);
	$this->db->or_like('tgl_lahir', $q);
	$this->db->or_like('nip', $q);
	$this->db->or_like('nidn', $q);
	$this->db->or_like('jk', $q);
	$this->db->or_like('golongan', $q);
	$this->db->or_like('gol_tmt', $q);
	$this->db->or_like('jabatan', $q);
	$this->db->or_like('jabatan_tmt', $q);
	$this->db->or_like('masa_kerja_tahun', $q);
	$this->db->or_like('masa_kerja_bulan', $q);
	$this->db->or_like('pendidikan', $q);
	$this->db->or_like('tahun_lulus', $q);
	$this->db->or_like('tingkat_ijazah', $q);
	$this->db->or_like('usia', $q);
	$this->db->or_like('catatan_mutasi', $q);
	$this->db->or_like('jenis_pd', $q);
	$this->db->or_like('userid', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('tempat_lahir', $q);
	$this->db->or_like('tgl_lahir', $q);
	$this->db->or_like('nip', $q);
	$this->db->or_like('nidn', $q);
	$this->db->or_like('jk', $q);
	$this->db->or_like('golongan', $q);
	$this->db->or_like('gol_tmt', $q);
	$this->db->or_like('jabatan', $q);
	$this->db->or_like('jabatan_tmt', $q);
	$this->db->or_like('masa_kerja_tahun', $q);
	$this->db->or_like('masa_kerja_bulan', $q);
	$this->db->or_like('pendidikan', $q);
	$this->db->or_like('tahun_lulus', $q);
	$this->db->or_like('tingkat_ijazah', $q);
	$this->db->or_like('usia', $q);
	$this->db->or_like('catatan_mutasi', $q);
	$this->db->or_like('jenis_pd', $q);
	$this->db->or_like('userid', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Master_model.php */
/* Location: ./application/models/Master_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-11-20 12:52:39 */
/* http://harviacode.com */