<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Arsip_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    /*
     * Get all arsip
     */
    function get_all_arsip($iddosen)
    {
        $query = $this->db->query("SELECT d.id AS id_dosen, d.nama, d.nip, a.id AS id_arsip, a.nama_dokumen, a.jenis_file, ad.id AS id_arsip_dosen, ad.terakhir_diubah, ad.url FROM dosen d, arsip a, arsip_dosen ad
        WHERE d.id=ad.id_dosen AND a.id=ad.id_arsip");
        return $query->result_array();
    }

    function search_dospeg($term){
        $this->db->like('nip',$term ,'both');
        $this->db->or_like('nama',$term,'both');
        $this->db->order_by('nama', 'ASC');
        $this->db->limit(10);
        return $this->db->get('dospeg')->result();
    }
        
    
}
